"""SQLAlchemy model for the `check_evidence` table."""

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class CheckEvidence(Base):
    """A photo-evidence record for a Reservation's check-in or check-out,
    per CLAUDE_BACKEND.md. Insert-only — nothing in this codebase ever
    updates or deletes a CheckEvidence row.

    Attributes:
        id: Primary key, generated by Postgres.
        reservation_id: The Reservation this evidence belongs to.
        type: One of check_in/check_out.
        photo_url: Evidence photo URL.
        notes: Optional description of the item's condition.
        created_at: When this evidence was recorded.
    """

    __tablename__ = "check_evidence"
    __table_args__ = (
        CheckConstraint("type IN ('check_in', 'check_out')", name="ck_check_evidence_type"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    reservation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("reservations.id"), nullable=False
    )
    type: Mapped[str] = mapped_column(String(20), nullable=False)
    photo_url: Mapped[str] = mapped_column(String, nullable=False)
    notes: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
