"""SQLAlchemy model for the `items` table."""

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.user import User


class Item(Base):
    """An item published by an owner, rentable by others.

    Attributes:
        id: Primary key, generated by Postgres (``gen_random_uuid()``).
        owner_id: The publishing user's id. Always set from the
            authenticated user's token, never from a request body.
        name: Short display name (e.g. "Taladro Bosch Professional").
        description: Full text description.
        category: One of the contract's CategoryEnum values, stored as a
            plain string — see Global Constraints for why this isn't a
            Postgres native enum type.
        price_per_day: Rental price in USD centavos. Must be positive,
            enforced both here (CHECK) and in the request schema.
        photo_url: URL to the item's photo, stored as-is.
        is_active: Soft-delete flag. False means hidden from search/detail.
        created_at: When the item was published, set by Postgres.
        owner: The publishing User, loaded via relationship (use
            ``joinedload(Item.owner)`` to avoid N+1 queries).
    """

    __tablename__ = "items"
    __table_args__ = (
        CheckConstraint("price_per_day > 0", name="ck_items_price_per_day_positive"),
        Index("idx_items_category", "category", postgresql_where=text("is_active = true")),
        Index(
            "idx_items_search",
            text("to_tsvector('simple', immutable_unaccent(name || ' ' || description))"),
            postgresql_using="gin",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    owner_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    price_per_day: Mapped[int] = mapped_column(Integer, nullable=False)
    photo_url: Mapped[str] = mapped_column(String, nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    owner: Mapped[User] = relationship()

    @property
    def owner_name(self) -> str:
        """The publishing owner's display name, via the ``owner`` relationship."""
        return self.owner.name
