"""SQLAlchemy model for the `reports` table."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Report(Base):
    """A problem report for a Reservation, per CLAUDE_BACKEND.md. Filing
    one freezes the reservation's deposit (see
    app.services.reports.report_problem). At most one Report exists per
    reservation, enforced by the reservation_id UNIQUE constraint below.

    Attributes:
        id: Primary key, generated by Postgres.
        reservation_id: The Reservation being reported. UNIQUE — the
            database-level half of the "one report per reservation"
            rule.
        reported_by: The User (owner or renter) who filed the report.
        reason: Free-text description of the problem.
        photo_url: Required evidence photo URL.
        created_at: When the report was filed.
    """

    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    reservation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("reservations.id"), nullable=False, unique=True
    )
    reported_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    reason: Mapped[str] = mapped_column(String, nullable=False)
    photo_url: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
