"""SQLAlchemy models for the `reservations` and `transactions` tables."""

import uuid
from datetime import date, datetime

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.item import Item
from app.models.user import User

BLOCKING_STATUSES = ("requested", "approved", "delivered", "returned")
"""Reservation statuses that count as "active" for double-booking
prevention and item-availability purposes — everything except
rejected/cancelled/closed. Matches the WHERE clause on the
no_double_booking EXCLUDE constraint and idx_reservations_item.
"""


class Reservation(Base):
    """A rental request/booking for an Item, moving through a status
    state machine (see CLAUDE_BACKEND.md). Deposit state is derived
    from the latest Transaction row, never cached here.

    Attributes:
        id: Primary key, generated by Postgres.
        item_id: The rented Item's id.
        renter_id: The requesting User's id. The owner is derived via
            item.owner_id — never denormalized onto this table.
        start_date: First day of the rental (inclusive).
        end_date: Last day of the rental (inclusive).
        status: One of requested/approved/delivered/returned/closed/rejected/cancelled.
        deposit_amount: price_per_day * inclusive day count, in centavos.
        created_at: When the reservation was requested.
        updated_at: Updated on every status transition.
        item: The rented Item, via relationship.
        renter: The requesting User, via relationship.
        transactions: This reservation's Transaction history, oldest
            first — use .deposit_status to read the derived state
            instead of touching this list directly.
    """

    __tablename__ = "reservations"
    __table_args__ = (
        CheckConstraint("end_date >= start_date", name="ck_reservations_end_after_start"),
        Index(
            "idx_reservations_item",
            "item_id",
            "start_date",
            "end_date",
            postgresql_where=text("status NOT IN ('rejected', 'cancelled', 'closed')"),
        ),
        Index("idx_reservations_renter", "renter_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("items.id"), nullable=False
    )
    renter_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    start_date: Mapped[date] = mapped_column(Date, nullable=False)
    end_date: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default=text("'requested'")
    )
    deposit_amount: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    item: Mapped[Item] = relationship()
    renter: Mapped[User] = relationship()
    transactions: Mapped[list["Transaction"]] = relationship(
        order_by="Transaction.created_at", back_populates="reservation"
    )

    @property
    def item_name(self) -> str:
        """The rented item's name, via the item relationship."""
        return self.item.name

    @property
    def item_photo_url(self) -> str:
        """The rented item's photo URL, via the item relationship."""
        return self.item.photo_url

    @property
    def renter_name(self) -> str:
        """The renter's display name, via the renter relationship."""
        return self.renter.name

    @property
    def deposit_status(self) -> str:
        """The deposit's current state, derived from the latest
        Transaction — never cached, per CLAUDE_BACKEND.md's "SACRED
        RULE" that the transactions table is the sole source of truth.

        Returns:
            "none" if no transaction exists yet, otherwise the status
            implied by the most recent transaction's type (hold ->
            held, release -> released, freeze -> frozen).
        """
        if not self.transactions:
            return "none"
        latest = self.transactions[-1]
        return {"hold": "held", "release": "released", "freeze": "frozen"}[latest.type]


class Transaction(Base):
    """An immutable deposit-ledger entry for a Reservation. INSERT only
    — nothing in this codebase ever updates or deletes a Transaction row.

    Attributes:
        id: Primary key, generated by Postgres.
        reservation_id: The Reservation this entry belongs to.
        type: One of hold/release/freeze.
        amount: In USD centavos.
        created_at: When this entry was recorded.
        reservation: The owning Reservation, via relationship.
    """

    __tablename__ = "transactions"
    __table_args__ = (
        CheckConstraint("type IN ('hold', 'release', 'freeze')", name="ck_transactions_type"),
        Index("idx_transactions_reservation", "reservation_id", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    reservation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("reservations.id"), nullable=False
    )
    type: Mapped[str] = mapped_column(String(20), nullable=False)
    amount: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    reservation: Mapped[Reservation] = relationship(back_populates="transactions")
