"""SQLAlchemy model for the `users` table."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class User(Base):
    """A registered account. Can act as an item owner, a renter, or both
    — there are no separate user roles in the data model.

    Attributes:
        id: Primary key, generated by Postgres (``gen_random_uuid()``).
        name: Display name shown to other users.
        email: Login identifier. Unique across all users.
        password_hash: bcrypt hash of the password. Never serialized in
            any API response.
        created_at: When the account was created, set by Postgres.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
