// Type declarations for non-TS imports, committed so CI's clean checkout
// can typecheck. (expo-env.d.ts covers these locally but is gitignored,
// generated by the Expo CLI — CI never has it.)

declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.css';
